### ISSUE TITLE
There is a error on  platform win10 and node v5.10.1

### ISSUE THREAD

**Issue by xinshouke** [mgcrea/babel-core#1]
Before I run my project on platform centos7 and node v4 very well, but I found the below error on  platform win10 and node v5.10.1:

E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "E:\koa2-demo-master\node_modules\runkoa/node_modules/babel-preset-es2015-node5" relative to directory "E:\koa2-demo-master\bin"
    at E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets (E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions (E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:307:14)
    at OptionManager.init (E:\koa2-demo-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:465:10)
    at compile (E:\koa2-demo-master\node_modules\babel-register\lib\node.js:81:45)
    at loader (E:\koa2-demo-master\node_modules\babel-register\lib\node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js](E:koa2-demo-masternode_modulesbabel-registerlibnode.js:136:7)
    at Module.load (module.js:357:32)

**Comment by xinshouke** [comment]
I fixed the issue as the [fix] issue@17koa/koa2-demo#1 [](https://github.com/wssgcg1213/runkoa/commit/dec4b8c19b7d5cf0d3e8afb63a5c92f174018ffa#comments)
